name: Sync tags on schedule
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout head repository
        uses: actions/checkout@v3

      - name: Checkout new tags to branches
        id: checkout-tags
        uses: chachako/checkout-tags@v1
        with:
          base: tribe29/checkmk

      - name: Push all new branches
        run: |
          while read branch; do
            ...
            git push origin $branch
          done <<< "${{ steps.checkout-tags.outputs.branches }}"
